<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/02_Creating_tensors_in_Tensorflow_using_tf_constant().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
scalar = tf.constant(10, dtype=tf.int64)

print(scalar)

tf.Tensor(10, shape=(), dtype=int64)


In [ ]:
tf.print(scalar)

10


In [ ]:
vector = [2, 4, 6, 8, 5]

vector_constant = tf.constant(vector)

In [ ]:
print(vector_constant)

tf.Tensor([2 4 6 8 5], shape=(5,), dtype=int32)


In [ ]:
vector_constant.ndim

1

In [ ]:
vector_constant.shape

TensorShape([5])

In [ ]:
matrix = tf.constant([
    [2, 4, 6, 8, 5],
    [2, 4, 6, 8, 5],
    [2, 4, 6, 8, 5],
])

In [ ]:
matrix

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[2, 4, 6, 8, 5],
       [2, 4, 6, 8, 5],
       [2, 4, 6, 8, 5]], dtype=int32)>

In [ ]:
3 * 5

15

In [ ]:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
tf.size(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.size(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
_tensor = [[[
    2, 4, 6, 8
]]]

tensor = tf.constant(_tensor)

In [ ]:
tensor

<tf.Tensor: shape=(1, 1, 4), dtype=int32, numpy=array([[[2, 4, 6, 8]]], dtype=int32)>

In [ ]:
[
    2, 4, 6, 8
]

[[
    3, 5, 7, 9
],

 [
     4, 6, 8, 10
 ]]

[[[
     3, 6, 9
 ],
  [2, 6, 9]
  ],
  [
      [4, 5, 6, 7],
      [3, 6, 9, 4
       ]]]

📓 **Note**


If we need, single dimensional array, then we will use single opening and closing square brackers, and value will go here.

If we need, 2 dimensional array, then we will use two opening and closing square brackers, and value will go inside the second square brackers only.

In the same way, use three opening and closing square brackers for a 3 dimensional array, and value will go inside the third square brackers only.

So, for 4 dimensional array, use four opening and closing square brackers for a 3 dimensional array, and value will go inside the 4th square brackers only.

In [ ]:
tensor

<tf.Tensor: shape=(1, 1, 4), dtype=int32, numpy=array([[[2, 4, 6, 8]]], dtype=int32)>

In [ ]:
tensor = tf.constant([

     [
         [
           3, 6, 9
         ],

         [
           3, 6, 9
         ]
    ],
     [
         [
          3, 6, 9
        ],

        [
          3, 6, 9
        ],
      ],
     [
         [
          3, 6, 9
          ],

         [
          3, 6, 9
          ]
         ],

     ])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[3, 6, 9],
        [3, 6, 9]],

       [[3, 6, 9],
        [3, 6, 9]],

       [[3, 6, 9],
        [3, 6, 9]]], dtype=int32)>

In [ ]:
3 * 2 * 3

18

In [ ]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=18>

In [ ]:
tensor = tf.constant([

     [
         [
           3, 6, 9, 10
         ],

         [
           3, 6, 9, 12
         ]
    ],
     [
         [
          3, 6, 9, 10
        ],

        [
          3, 6, 9, 10
        ],
      ],
     [
         [
          3, 6, 9, 11
          ],

         [
          3, 6, 9, 12
          ]
         ],

     ])