<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/03_Creating_tensors_in_Tensorflow_using_tf_Variable().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

scalar = tf.Variable(99)

In [ ]:
print(scalar)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=99>


In [ ]:
scalar.shape

TensorShape([])

In [ ]:
vector = tf.Variable([12, 33, 45, 66], dtype=float)

In [ ]:
vector

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([12., 33., 45., 66.], dtype=float32)>

In [ ]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
matrix = tf.Variable([
    [
      2, 3, 4, 5
    ],
    [
      6, 7, 8, 9
    ],
    [
      11, 22, 33, 44
    ]
])

In [ ]:
matrix

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [11, 22, 33, 44]], dtype=int32)>

In [ ]:
3 * 4

12

In [ ]:
matrix.shape

TensorShape([3, 4])

In [ ]:
tf.size(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
tf.rank(matrix)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tensor = tf.Variable([
    [
        [
            1, 2, 3, 4
        ],

        [
            1, 2, 3, 4
        ],
        [
            1, 2, 3, 4
        ]
    ],
    [
        [
            1, 2, 3, 4
        ],
        [
            1, 2, 3, 4
        ],
        [
            1, 2, 3, 4
        ]
    ],


    [
        [
            1, 2, 3, 4
        ],
        [
            1, 2, 3, 4
        ],
        [
            1, 2, 3, 4
        ]
    ],

])

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(3, 3, 4) dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]], dtype=int32)>

In [ ]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=36>

In [ ]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
constant_vector = tf.constant([1, 2, 3, 4])

In [ ]:
constant_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
constant_vector[0] = 11

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
vector

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([12., 33., 45., 66.], dtype=float32)>

In [ ]:
vector[0] = 123

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
vector[0].assign(123)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=float32, numpy=array([123.,  33.,  45.,  66.], dtype=float32)>

In [ ]:
constant_vector[0].assign(111)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'