<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/04_zeros()%2C_ones()_range()%2C_tensors_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

vector = tf.zeros(10, dtype=tf.int32)

In [ ]:
vector

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>

In [ ]:
matrix = tf.zeros((5, 6))

In [ ]:
matrix

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tensor = tf.zeros((2, 3, 4))

In [ ]:
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
tensor.shape

TensorShape([2, 3, 4])

In [ ]:
tensor.ndim

3

In [ ]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
ones = tf.ones((2, 3))

In [ ]:
ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
ones_vector = tf.ones(10)

In [ ]:
ones_vector

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
tf.size(ones_vector)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
ones_tensor =tf.ones((3, 4, 5))

In [ ]:
ones_tensor

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
range_vector = tf.range(10, 51, 5)

In [ ]:
range_vector

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([10, 15, 20, 25, 30, 35, 40, 45, 50], dtype=int32)>