<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/05_math_reduce_mean()%2C_math_reduce_std()%2C_random_normal()%2C_and_random_uniform()_tensors_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

range_vector = tf.range(11)

In [ ]:
range_vector

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [ ]:
sum_of_range_vector = 0
counter = 0
for index in range_vector:
  sum_of_range_vector += range_vector[index]
  counter += 1

print(sum_of_range_vector)
print('counter of elements')
print(counter)

tf.Tensor(55, shape=(), dtype=int32)
counter of elements
11


In [ ]:
tf.size(range_vector)

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [ ]:
mean = sum_of_range_vector / counter

In [ ]:
mean

<tf.Tensor: shape=(), dtype=float64, numpy=5.0>

In [ ]:
# standard_deviation = sqrt(mean(x)), where x = abs(a - a.mean()) ** 2
sum_of_square = 0
for index in range_vector:
  sum_of_square += tf.math.square(range_vector[index] - tf.cast(mean, tf.int32))
  print(sum_of_square)

print(sum_of_square)

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(41, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor(54, shape=(), dtype=int32)
tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(56, shape=(), dtype=int32)
tf.Tensor(60, shape=(), dtype=int32)
tf.Tensor(69, shape=(), dtype=int32)
tf.Tensor(85, shape=(), dtype=int32)
tf.Tensor(110, shape=(), dtype=int32)
tf.Tensor(110, shape=(), dtype=int32)


In [ ]:
x = abs(a - a.mean()) ** 2
sqrt(mean(x))

In [ ]:
mean_of_sum_of_square = sum_of_square / 11

In [ ]:
tf.math.sqrt(mean_of_sum_of_square)

<tf.Tensor: shape=(), dtype=float64, numpy=3.1622776601683795>

In [ ]:
tf.math.reduce_mean(range_vector)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
tf.math.reduce_std(tf.cast(range_vector, float))

<tf.Tensor: shape=(), dtype=float32, numpy=3.1622777>

In [ ]:
tf.random

<module 'tensorflow._api.v2.random' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/random/__init__.py'>

In [ ]:
random_normal_matrix = tf.random.normal((2, 3), 50, 10)

In [ ]:
random_normal_matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[36.279495, 69.860176, 60.13775 ],
       [51.99407 , 55.621773, 23.016193]], dtype=float32)>

In [ ]:
tf.math.reduce_mean(random_normal_matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=49.48491>

In [ ]:
tf.math.reduce_std(random_normal_matrix)

<tf.Tensor: shape=(), dtype=float32, numpy=15.532586>

In [ ]:
random_uniform_tensor = tf.random.uniform((2, 3, 4, 5), 10, 20)

In [ ]:
random_uniform_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[16.969536 , 18.165861 , 10.641481 , 14.348257 , 11.278659 ],
         [12.277781 , 10.69332  , 13.118581 , 10.370537 , 19.392632 ],
         [10.676558 , 19.531271 , 18.890564 , 10.140581 , 19.27284  ],
         [11.238642 , 17.005697 , 17.013897 , 14.757738 , 10.515704 ]],

        [[17.971788 , 11.223578 , 19.150106 , 13.4282255, 12.256289 ],
         [19.09839  , 10.4438   , 15.716691 , 16.089222 , 19.836237 ],
         [17.919407 , 12.127324 , 15.619887 , 11.331744 , 10.755458 ],
         [18.576885 , 12.591103 , 11.303563 , 10.783143 , 15.143189 ]],

        [[16.204733 , 15.1052685, 16.4279   , 19.320965 , 13.557304 ],
         [13.468697 , 19.582218 , 16.772943 , 12.356273 , 12.545037 ],
         [11.846318 , 14.591562 , 15.016985 , 16.117548 , 16.632381 ],
         [14.548554 , 10.460394 , 15.978879 , 11.413201 , 11.495831 ]]],


       [[[11.883674 , 18.479752 , 14.792775 , 15.446911 , 12.413884 ],
         [11.68

In [ ]:
tf.math.reduce_mean(random_uniform_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=14.6666155>

In [ ]:
tf.math.reduce_std(random_uniform_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0715656>