<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/06_random_shuffle()%2C_tf_reshape()%2C_flatten_and_tf_cast()_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

matrix = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
    [17, 18, 19, 20],
    [21, 22, 23, 24],
])

In [ ]:
matrix

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

In [ ]:
tf.random.shuffle(matrix)

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[21, 22, 23, 24],
       [17, 18, 19, 20],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)>

In [ ]:
6*4

24

In [ ]:
print(4 * 6)
print(3 * 8)
print(2 * 12)

24
24
24


In [ ]:
reshaped_matrix = tf.reshape(matrix, (2, 12))

In [ ]:
flatten_matrix = tf.reshape(matrix, -1)

In [ ]:
tf.cast(matrix, float)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.],
       [17., 18., 19., 20.],
       [21., 22., 23., 24.]], dtype=float32)>

In [ ]:
reshaped_matrix

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
flatten_matrix

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>