<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/07_Indexing_and_slicing_tensors_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

tensor_2d = tf.random.uniform((6, 3), 15, 25)

In [ ]:
tensor_2d

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[23.087559, 23.870079, 21.774235],
       [21.752235, 22.436668, 23.43544 ],
       [16.407106, 18.084555, 16.68509 ],
       [18.602074, 24.78664 , 16.957996],
       [16.09517 , 15.138202, 22.29373 ],
       [19.782791, 17.94619 , 17.712751]], dtype=float32)>

In [ ]:
tensor_2d.ndim

2

In [ ]:
tensor_2d[0:, 0]

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([23.087559, 21.752235, 16.407106, 18.602074, 16.09517 , 19.782791],
      dtype=float32)>

In [ ]:
tensor = tf.random.uniform((2, 3, 4), 50, 99)

In [ ]:
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[63.06982 , 81.024895, 62.14735 , 50.128963],
        [62.396072, 83.02233 , 78.856155, 74.0378  ],
        [53.580597, 59.78082 , 58.130665, 98.80684 ]],

       [[67.83786 , 82.73725 , 82.00577 , 93.41356 ],
        [89.119736, 59.929363, 97.7941  , 69.47641 ],
        [73.58825 , 85.34027 , 71.63492 , 50.83861 ]]], dtype=float32)>

In [ ]:
tensor.ndim

3

In [ ]:
tensor[0:, 0:, 1:3]

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[81.024895, 62.14735 ],
        [83.02233 , 78.856155],
        [59.78082 , 58.130665]],

       [[82.73725 , 82.00577 ],
        [59.929363, 97.7941  ],
        [85.34027 , 71.63492 ]]], dtype=float32)>