<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/08_Basic_Arithmetic_Operations%2C_Aggregations_and_Math_functions_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

scalar_a = 100
scalar_b = 200

scalar_a + scalar_b

300

In [ ]:
result = tf.add(scalar_a, scalar_b)

In [ ]:
tf.print(result)

300


In [ ]:
scalar_a * scalar_b

20000

In [ ]:
tf.multiply(scalar_a, scalar_b)

<tf.Tensor: shape=(), dtype=int32, numpy=20000>

In [ ]:
vector_a = tf.range(10)

In [ ]:
vector_a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
vector_b = tf.range(20, 30)

In [ ]:
vector_b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>

In [ ]:
vector_a + vector_b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38], dtype=int32)>

In [ ]:
tf.add(vector_a, vector_b)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38], dtype=int32)>

In [ ]:
vector_a * vector_b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261], dtype=int32)>

In [ ]:
tf.multiply(vector_a, vector_b)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261], dtype=int32)>

In [ ]:
matrix_a = tf.random.normal((2, 3),50, 5)
matrix_b = tf.random.normal((2, 3), 100, 15)

In [ ]:
matrix_a + matrix_b

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[170.02783, 144.24799, 157.93274],
       [166.9415 , 168.77492, 120.13513]], dtype=float32)>

In [ ]:
matrix_a, matrix_b

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[54.493664, 52.49677 , 50.10245 ],
        [56.39789 , 58.886425, 50.40931 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[115.53417,  91.75121, 107.83029],
        [110.54361, 109.88849,  69.72582]], dtype=float32)>)

In [ ]:
tf.add(matrix_a, matrix_b)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[170.02783, 144.24799, 157.93274],
       [166.9415 , 168.77492, 120.13513]], dtype=float32)>

In [ ]:
tf.multiply(matrix_a, matrix_b)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[6295.8804, 4816.642 , 5402.562 ],
       [6234.4263, 6470.9404, 3514.8306]], dtype=float32)>

In [ ]:
tensor_a = tf.random.normal((2, 3, 4), 150, 20)
tensor_b = tf.random.normal((2, 3, 4), 250, 30)

In [ ]:
tensor_a + tensor_b

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[409.84857, 450.93665, 477.7663 , 367.8205 ],
        [352.3324 , 391.49554, 392.0163 , 442.202  ],
        [412.48364, 394.70386, 401.89157, 392.2453 ]],

       [[447.7849 , 383.27258, 428.20886, 391.70557],
        [463.95544, 354.4021 , 433.48212, 395.53412],
        [395.78564, 400.2749 , 442.61652, 373.80313]]], dtype=float32)>

In [ ]:
x = tf.range(10)
y = tf.range(20)

In [ ]:
x,y

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(20,), dtype=int32, numpy=
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19], dtype=int32)>)

In [ ]:
x + y

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [10] vs. [20] [Op:AddV2] name: 

In [ ]:
tf.add(x, y)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [10] vs. [20] [Op:AddV2] name: 

In [ ]:
x = tf.random.normal((2, 3), 50, 10)
y = tf.random.normal((2, 4), 50, 10)

In [ ]:
x + y

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [2,3] vs. [2,4] [Op:AddV2] name: 

# **So, shapes and size must be same for both the tensors**

In [ ]:
x = tf.random.normal((2, 3), 50, 10)
y = tf.random.normal((2, 3), 100, 15)

In [ ]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[58.98523 , 35.04337 , 51.591022],
       [46.751003, 56.548714, 42.768707]], dtype=float32)>

In [ ]:
tf.reduce_min(x)

<tf.Tensor: shape=(), dtype=float32, numpy=35.04337>

In [ ]:
tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=float32, numpy=58.98523>

In [ ]:
tf.reduce_mean(x)

<tf.Tensor: shape=(), dtype=float32, numpy=48.614674>

In [ ]:
tf.math.reduce_std(x)

<tf.Tensor: shape=(), dtype=float32, numpy=8.177051>

In [ ]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=291.68805>

In [ ]:
tf.square(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3479.2573, 1228.0377, 2661.6335],
       [2185.6562, 3197.757 , 1829.1624]], dtype=float32)>

In [ ]:
tf.sqrt(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[7.6801844, 5.919744 , 7.182689 ],
       [6.8374705, 7.519888 , 6.5397787]], dtype=float32)>

In [ ]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[58.98523 , 35.04337 , 51.591022],
       [46.751003, 56.548714, 42.768707]], dtype=float32)>

In [ ]:
tf.round(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[59., 35., 52.],
       [47., 57., 43.]], dtype=float32)>

In [ ]:
tf.math.ceil(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[59., 36., 52.],
       [47., 57., 43.]], dtype=float32)>

In [ ]:
tf.math.floor(x)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[58., 35., 51.],
       [46., 56., 42.]], dtype=float32)>

In [ ]:
vector = tf.range(-10, 20)

In [ ]:
vector

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19], dtype=int32)>

In [ ]:
tf.abs(vector)

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int32)>