<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/09_tf_math_argmax()%2C_tf_math_argmin()%2C_tf_math_equal()%2C_tf_math_not_equal()%2C_tf_math_greater()%2C_tf_math_greater_equal()_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

vector = tf.range(10)

In [ ]:
vector

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.math.argmax(vector)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [ ]:
matrix = tf.random.normal((2, 3), 50, 10)

In [ ]:
matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[62.002007, 28.243927, 37.483284],
       [40.520775, 42.46566 , 62.312206]], dtype=float32)>

In [ ]:
tf.math.argmax(matrix)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 1])>

In [ ]:
tf.math.argmax(matrix, axis = 0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 1])>

In [ ]:
tf.math.argmax(matrix, axis = 1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 2])>

In [ ]:
tf.math.argmin(vector)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.math.argmin(matrix)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 0])>

In [ ]:
matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[62.002007, 28.243927, 37.483284],
       [40.520775, 42.46566 , 62.312206]], dtype=float32)>

In [ ]:
tf.math.argmin(matrix, axis = 1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [ ]:
x = tf.constant([2, 3, 4, 5])
y = tf.constant([2, 3, 4, 6])
tf.math.not_equal(x, y)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([False, False, False,  True])>

In [ ]:
x = tf.constant([3, 3, 4, 5])
y = tf.constant([2, 3, 4, 6])
tf.math.greater_equal(x, y)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True, False])>