<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/10_tf_math_reduce_prod()%2C_tf_math_reduce_variance()%2C_tf_linalg_matmul()_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

vector = tf.range(10)

In [ ]:
vector

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.math.reduce_prod(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
x = tf.constant([2, 3, 4])

In [ ]:
tf.math.reduce_prod(x)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
for v in x:
  print(v)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
m = 1

for v in x:
  m = m * v

In [ ]:
print(m)

tf.Tensor(24, shape=(), dtype=int32)


In [ ]:
2 * 3 * 4

24

In [ ]:
y = tf.math.reduce_variance(tf.cast(x, dtype=float))

In [ ]:
print(y)

tf.Tensor(0.6666667, shape=(), dtype=float32)


In [ ]:
vector = tf.constant([7, 8, 3])

In [ ]:
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 3], dtype=int32)>

In [ ]:
tf.math.reduce_variance(tf.cast(vector, dtype=float))

<tf.Tensor: shape=(), dtype=float32, numpy=4.6666665>

In [ ]:
∑(xi - mean)²
-------------
    N

In [ ]:
(7 + 8 + 3) / 3

6.0

In [ ]:
sqr = tf.square(7 - 6) + tf.square(8 - 6) + tf.square(3 - 6)

In [ ]:
sqr

<tf.Tensor: shape=(), dtype=int32, numpy=14>

In [ ]:
sqr / 3

<tf.Tensor: shape=(), dtype=float64, numpy=4.666666666666667>

In [ ]:
x = tf.constant([[2, 3, 4], [5, 6, 7]])
y = tf.constant([[2, 3, 4], [5, 6, 7], [3, 5, 9]])

In [ ]:
x @ y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 31,  44,  65],
       [ 61,  86, 125]], dtype=int32)>

In [ ]:
x = tf.constant([[2, 3], [5, 6]])
y = tf.constant([[2, 3], [5, 6]])

In [ ]:
x @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 24],
       [40, 51]], dtype=int32)>

In [ ]:
x = tf.random.normal((8, 3), 50, 10)
y = tf.random.normal((3, 8), 50, 10)

In [ ]:
tf.linalg.matmul(y, x)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[18969.557, 18230.773, 18662.984],
       [20611.889, 19960.77 , 19273.268],
       [20973.672, 20524.236, 20248.62 ]], dtype=float32)>