<a href="https://colab.research.google.com/github/NeuralFolk/tensorflow-basic/blob/main/11_tf_transpose()%2C_tf_split()%2C_tf_reverse()%2C_tf_sort()_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

vector = tf.range(10)

In [ ]:
vector

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.transpose(vector)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
matrix = tf.random.normal((2, 3), 50, 10)

In [ ]:
matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[53.66564 , 55.906303, 44.84543 ],
       [68.466484, 50.884724, 60.544243]], dtype=float32)>

In [ ]:
tf.transpose(matrix)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[53.66564 , 68.466484],
       [55.906303, 50.884724],
       [44.84543 , 60.544243]], dtype=float32)>

In [ ]:
x = tf.constant([[2, 3], [4, 5], [7, 8]])

In [ ]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [7, 8]], dtype=int32)>

In [ ]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 4, 7],
       [3, 5, 8]], dtype=int32)>

In [ ]:
vector = tf.range(20)

In [ ]:
vector

<tf.Tensor: shape=(20,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int32)>

In [ ]:
tf.split(vector, num_or_size_splits = 4, axis = 0)

[<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 11, 12, 13, 14], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([15, 16, 17, 18, 19], dtype=int32)>]

In [ ]:
matrix = tf.random.normal((2, 3), 10, 2)

In [ ]:
matrix

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10.94007 ,  9.253694, 10.06596 ],
       [ 9.669955, 10.061029, 12.076046]], dtype=float32)>

In [ ]:
tf.split(matrix, num_or_size_splits = 2, axis = 0)

[<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[10.94007 ,  9.253694, 10.06596 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 9.669955, 10.061029, 12.076046]], dtype=float32)>]

In [ ]:
tf.split(matrix, num_or_size_splits = 3, axis = 1)

[<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[10.94007 ],
        [ 9.669955]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[ 9.253694],
        [10.061029]], dtype=float32)>,
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[10.06596 ],
        [12.076046]], dtype=float32)>]

In [ ]:
matrix = tf.random.normal((12, 12), 10, 2)

In [ ]:
matrix

<tf.Tensor: shape=(12, 12), dtype=float32, numpy=
array([[ 9.212806 ,  9.600187 , 11.792709 ,  9.794576 ,  9.170592 ,
         9.523257 , 10.748522 ,  9.652939 , 10.772305 , 10.019805 ,
         7.3946238,  8.4904175],
       [15.491488 , 12.470431 ,  7.239174 ,  8.994104 ,  6.954004 ,
        13.403208 , 10.333908 , 14.571619 , 13.299152 ,  6.4089494,
         7.6392527, 10.692793 ],
       [11.892656 ,  9.007846 ,  9.771195 ,  8.6016655,  9.376345 ,
         9.05586  , 12.72337  ,  8.993532 , 11.799126 , 10.849277 ,
         8.089203 , 11.451077 ],
       [10.079139 ,  7.960721 , 14.206173 ,  7.1039524, 11.663934 ,
         9.948452 ,  8.003453 , 11.644338 ,  7.1127243, 11.259592 ,
        13.680862 ,  8.586615 ],
       [11.90156  , 14.077655 , 12.853793 ,  7.6944637, 10.292928 ,
        12.881308 ,  8.152776 ,  8.664157 ,  8.250501 , 11.565506 ,
        10.816373 ,  9.132544 ],
       [12.335098 , 10.643862 ,  9.285866 ,  7.0153556, 12.061892 ,
        15.296506 , 11.677439 , 10.49

In [ ]:
tf.split(matrix, num_or_size_splits = 2, axis = 0)

[<tf.Tensor: shape=(6, 12), dtype=float32, numpy=
 array([[ 9.212806 ,  9.600187 , 11.792709 ,  9.794576 ,  9.170592 ,
          9.523257 , 10.748522 ,  9.652939 , 10.772305 , 10.019805 ,
          7.3946238,  8.4904175],
        [15.491488 , 12.470431 ,  7.239174 ,  8.994104 ,  6.954004 ,
         13.403208 , 10.333908 , 14.571619 , 13.299152 ,  6.4089494,
          7.6392527, 10.692793 ],
        [11.892656 ,  9.007846 ,  9.771195 ,  8.6016655,  9.376345 ,
          9.05586  , 12.72337  ,  8.993532 , 11.799126 , 10.849277 ,
          8.089203 , 11.451077 ],
        [10.079139 ,  7.960721 , 14.206173 ,  7.1039524, 11.663934 ,
          9.948452 ,  8.003453 , 11.644338 ,  7.1127243, 11.259592 ,
         13.680862 ,  8.586615 ],
        [11.90156  , 14.077655 , 12.853793 ,  7.6944637, 10.292928 ,
         12.881308 ,  8.152776 ,  8.664157 ,  8.250501 , 11.565506 ,
         10.816373 ,  9.132544 ],
        [12.335098 , 10.643862 ,  9.285866 ,  7.0153556, 12.061892 ,
         15.296506 , 

In [ ]:
vector = tf.range(10)

In [ ]:
vector

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.reverse(vector, axis = [0])

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [ ]:
tf.reverse(vector, axis = [1])

InvalidArgumentError: {{function_node __wrapped__ReverseV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} 'axis'[0] = 1 is out of valid range [0, 0 [Op:ReverseV2]

In [ ]:
matrix = tf.random.normal((3, 3), 20, 3)

In [ ]:
matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[18.269663, 23.695684, 21.257158],
       [22.457224, 18.58074 , 20.9263  ],
       [17.129005, 20.717403, 18.289665]], dtype=float32)>

In [ ]:
tf.reverse(matrix, axis = [0])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[17.129005, 20.717403, 18.289665],
       [22.457224, 18.58074 , 20.9263  ],
       [18.269663, 23.695684, 21.257158]], dtype=float32)>

In [ ]:
tf.reverse(matrix, axis = [1])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[21.257158, 23.695684, 18.269663],
       [20.9263  , 18.58074 , 22.457224],
       [18.289665, 20.717403, 17.129005]], dtype=float32)>

In [ ]:
tf.reverse(matrix, axis = [2])

InvalidArgumentError: {{function_node __wrapped__ReverseV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} 'axis'[0] = 2 is out of valid range [0, 1 [Op:ReverseV2]

In [ ]:
matrix.ndim

2

In [ ]:
tensor = tf.random.normal((2, 3, 4), 30, 3)

In [ ]:
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[25.328594, 27.359062, 29.315594, 32.751015],
        [31.355442, 31.958775, 33.46046 , 26.875086],
        [27.547565, 25.291004, 31.506788, 27.665552]],

       [[30.21577 , 38.51346 , 30.759115, 26.556084],
        [26.945305, 36.987434, 33.073284, 28.620106],
        [32.064266, 29.688057, 27.698158, 29.501705]]], dtype=float32)>

In [ ]:
tf.reverse(tensor, axis = [0])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[30.21577 , 38.51346 , 30.759115, 26.556084],
        [26.945305, 36.987434, 33.073284, 28.620106],
        [32.064266, 29.688057, 27.698158, 29.501705]],

       [[25.328594, 27.359062, 29.315594, 32.751015],
        [31.355442, 31.958775, 33.46046 , 26.875086],
        [27.547565, 25.291004, 31.506788, 27.665552]]], dtype=float32)>

In [ ]:
tf.reverse(tensor, axis = [1])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[27.547565, 25.291004, 31.506788, 27.665552],
        [31.355442, 31.958775, 33.46046 , 26.875086],
        [25.328594, 27.359062, 29.315594, 32.751015]],

       [[32.064266, 29.688057, 27.698158, 29.501705],
        [26.945305, 36.987434, 33.073284, 28.620106],
        [30.21577 , 38.51346 , 30.759115, 26.556084]]], dtype=float32)>

In [ ]:
tf.reverse(tensor, axis = [2])

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[32.751015, 29.315594, 27.359062, 25.328594],
        [26.875086, 33.46046 , 31.958775, 31.355442],
        [27.665552, 31.506788, 25.291004, 27.547565]],

       [[26.556084, 30.759115, 38.51346 , 30.21577 ],
        [28.620106, 33.073284, 36.987434, 26.945305],
        [29.501705, 27.698158, 29.688057, 32.064266]]], dtype=float32)>

In [ ]:
tf.reverse(tensor, axis = [3])

InvalidArgumentError: {{function_node __wrapped__ReverseV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} 'axis'[0] = 3 is out of valid range [0, 2 [Op:ReverseV2]

In [ ]:
tensor.ndim

3

In [ ]:
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[25.328594, 27.359062, 29.315594, 32.751015],
        [31.355442, 31.958775, 33.46046 , 26.875086],
        [27.547565, 25.291004, 31.506788, 27.665552]],

       [[30.21577 , 38.51346 , 30.759115, 26.556084],
        [26.945305, 36.987434, 33.073284, 28.620106],
        [32.064266, 29.688057, 27.698158, 29.501705]]], dtype=float32)>

In [ ]:
tf.sort(tensor)

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[25.328594, 27.359062, 29.315594, 32.751015],
        [26.875086, 31.355442, 31.958775, 33.46046 ],
        [25.291004, 27.547565, 27.665552, 31.506788]],

       [[26.556084, 30.21577 , 30.759115, 38.51346 ],
        [26.945305, 28.620106, 33.073284, 36.987434],
        [27.698158, 29.501705, 29.688057, 32.064266]]], dtype=float32)>